
package proveedor.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "WebServiceFacadeBeanService", targetNamespace = "http://servicios/", wsdlLocation = "http://localhost:8080/proveedorEAR-proveedorEJB/WebServiceFacadeBean?wsdl")
public class WebServiceFacadeBeanService
    extends Service
{

    private final static URL WEBSERVICEFACADEBEANSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/proveedorEAR-proveedorEJB/WebServiceFacadeBean?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WEBSERVICEFACADEBEANSERVICE_WSDL_LOCATION = url;
    }

    public WebServiceFacadeBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceFacadeBeanService() {
        super(WEBSERVICEFACADEBEANSERVICE_WSDL_LOCATION, new QName("http://servicios/", "WebServiceFacadeBeanService"));
    }

    /**
     * 
     * @return
     *     returns WebServiceFacadeBean
     */
    @WebEndpoint(name = "WebServiceFacadeBeanPort")
    public WebServiceFacadeBean getWebServiceFacadeBeanPort() {
        return (WebServiceFacadeBean)super.getPort(new QName("http://servicios/", "WebServiceFacadeBeanPort"), WebServiceFacadeBean.class);
    }

}
