
package casaCentral.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "RemoteSessionBeanService", targetNamespace = "http://webservice.casacentral.ejb/", wsdlLocation = "http://localhost:8080/casaCentralEAR-casaCentralEJB/RemoteSessionBean?wsdl")
public class RemoteSessionBeanService
    extends Service
{

    private final static URL REMOTESESSIONBEANSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/casaCentralEAR-casaCentralEJB/RemoteSessionBean?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        REMOTESESSIONBEANSERVICE_WSDL_LOCATION = url;
    }

    public RemoteSessionBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RemoteSessionBeanService() {
        super(REMOTESESSIONBEANSERVICE_WSDL_LOCATION, new QName("http://webservice.casacentral.ejb/", "RemoteSessionBeanService"));
    }

    /**
     * 
     * @return
     *     returns RemoteSessionBean
     */
    @WebEndpoint(name = "RemoteSessionBeanPort")
    public RemoteSessionBean getRemoteSessionBeanPort() {
        return (RemoteSessionBean)super.getPort(new QName("http://webservice.casacentral.ejb/", "RemoteSessionBeanPort"), RemoteSessionBean.class);
    }

}
