
package casaCentral.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "RemoteSessionBean", targetNamespace = "http://webservice.casacentral.ejb/")
public interface RemoteSessionBean {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cotizarRodamiento", targetNamespace = "http://webservice.casacentral.ejb/", className = "casaCentral.webservice.CotizarRodamiento")
    @ResponseWrapper(localName = "cotizarRodamientoResponse", targetNamespace = "http://webservice.casacentral.ejb/", className = "casaCentral.webservice.CotizarRodamientoResponse")
    public String cotizarRodamiento(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "nuevoRodamiento", targetNamespace = "http://webservice.casacentral.ejb/", className = "casaCentral.webservice.NuevoRodamiento")
    @ResponseWrapper(localName = "nuevoRodamientoResponse", targetNamespace = "http://webservice.casacentral.ejb/", className = "casaCentral.webservice.NuevoRodamientoResponse")
    public String nuevoRodamiento(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
